version: '3'
# based on https://learn.microsoft.com/en-us/azure/ai-services/content-understanding/quickstart/use-rest-api?tabs=video
env:
  RG: content_understanding
  LOCATION: swedencentral
  AI_RESOURCE_NAME: ai-svc-vsscdy7uosaws
dotenv: ['.env']

tasks:
  azure_auth:
    desc: "Authenticate to Azure using Azure CLI"
    cmds:
      - az login
    silent: false
  create_resource_group:
    desc: "Create a resource group ${RG} in $LOCATION"
    cmds:
      - az group create --name $RG --location $LOCATION
    silent: false
  deploy_ai_services:
    #deps: [create_resource_group]
    desc: "Deploy AI Services"
    cmds:
      - az deployment group create --resource-group $RG --template-file main.bicep
    silent: false
  
  output_values:
    cmds:
      - az deployment group show  --resource-group $RG -n main --query properties.outputs
    silent: false
  
  gen_dot_env:
    cmds:
      - echo "export AI_RESOURCE_NAME=$AI_RESOURCE_NAME" > .env
      - echo "export AI_RESOURCE_KEY=$(az cognitiveservices account keys list --name $AI_RESOURCE_NAME --resource-group $RG --query key1 -o tsv)" >> .env
      - echo "export AI_RESOURCE_ENDPOINT=$(az cognitiveservices account show --name $AI_RESOURCE_NAME --resource-group $RG --query properties.endpoint -o tsv)" >> .env
    silent: false
  
  list_analyser:
    desc: "list available analyser"
    #deps: [config]
    cmds:
      -  ./list_analyzer.sh 
    silent: false
 
  new_analyser:
    desc: "Deployer a new custom analyser"
    #deps: [config]
    cmds:
      -  ./create_analyzer.sh my_video_analyzer ./custom_video_analyser.json 
    silent: false

  analyze_video:
    desc: "Analyse a video"
    #deps: [config]
    cmds:
      -  ./analyze_video.sh my_video_analyzer https://github.com/bmoussaud/azure-ai-tips/raw/refs/heads/main/content-understanding/sample_pancakes.mp4.mp4
    silent: false

  get_analyze_video:
    desc: "Get The Analyse of a video"
    cmds:
      -  ./get_analyze_video.sh my_video_analyzer 33a5dea7-55f2-4787-b732-30c105f9b46b
    silent: false

  
  clean_up:
    desc: "Clean up"
    cmds:
      - az cognitiveservices account delete -n $AI_RESOURCE_NAME -g $RG
      - az cognitiveservices account purge -n $AI_RESOURCE_NAME -g $RG -l $LOCATION
      - az group delete --name $RG --yes
    silent: false